"""initial schema

Revision ID: 7548058d9410
Revises: 
Create Date: 2026-07-06 09:50:14.358562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7548058d9410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_sub', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('referral',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_sub', sa.String(), nullable=False),
    sa.Column('referred_sub', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'joined', 'first_submission_done', name='referral_status'), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_sub', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'business', 'customer', name='user_roles'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_keycloak_sub'), 'user_profile', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_user_profile_phone_number'), 'user_profile', ['phone_number'], unique=True)
    op.create_table('business',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_sub', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(length=150), nullable=True),
    sa.Column('detailed_description', sa.String(length=1000), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('landline_number', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('business_timings', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='business_status'), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['owner_sub'], ['user_profile.keycloak_sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('logo', 'cover_photo', 'gallery_image', 'video', name='media_type'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_sub', sa.String(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='receipt_status'), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_sub', sa.String(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_category', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('total_business_taken', sa.Float(), nullable=True),
    sa.Column('total_business_given', sa.Float(), nullable=True),
    sa.Column('business_count', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('s_member_induction', sa.String(), nullable=True),
    sa.Column('b_member_induction', sa.String(), nullable=True),
    sa.Column('total_rewards_gained', sa.Integer(), nullable=True),
    sa.Column('benefit_claim_status', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('joined_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beneficiary_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('total_business_given', sa.Float(), nullable=True),
    sa.Column('s_member_induction', sa.String(), nullable=True),
    sa.Column('b_member_induction', sa.String(), nullable=True),
    sa.Column('total_rewards_gained', sa.Integer(), nullable=True),
    sa.Column('benefit_claim_status', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('subscriber_name', sa.String(), nullable=True),
    sa.Column('subscriber_id', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('jobs_taken', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward')
    op.drop_table('receipt')
    op.drop_table('business_media')
    op.drop_table('business')
    op.drop_index(op.f('ix_user_profile_phone_number'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_keycloak_sub'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_table('referral')
    op.drop_table('category')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
